variables:
    IMAGE_NAME: profakymbo/myportfolio
    IMAGE_TAG: latest

stages:
    - "test"
    - "build"
    - "deploy"

run_tests:
    stage: test
    script:
        - 

build_image:
    stage: build
    image: docker:23.0.1-cli
    services:
        - docker:23.0.1-dind
    script: 
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

deploy_terraform_config_and_manifests:
    image: ubuntu:22.10
    stage: deploy
    before_script:
        - chmod +x before_deploy.sh
        - chmod +x deploy.sh
        - ./before_deploy.sh
        - curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64
        - chmod +x ./aws-iam-authenticator
        - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
        - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
        - aws-iam-authenticator help
    script: 
        - ./deploy.sh

