apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio-github
  labels:
    app: myportfolio
spec:
  selector:
    matchLabels:
        app: myportfolio
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
        - name: myportfolio
          image: 502929775835.dkr.ecr.us-east-1.amazonaws.com/myportfolio:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
