apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio-deployment
  labels:
    app: myportfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myportfolio
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
      - name: myportfolio
        image: profakymbo/myportfolio
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myportfolio-service
spec:
  selector:
    app: myportfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort  