apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio-deployment
  labels:
    app: myportfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myportfolio
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
      - name: myportfolio
        image: profakymbo/myportfolio
        ports:
        - containerPort: 80