apiVersion: v1
kind: Service
metadata:
  name: myportfolio-service
spec:
  selector:
    app: myportfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort  